import 'package:classpay/core/theme/app_theme.dart';
import 'package:classpay/models/class_record.dart';
import 'package:classpay/providers/class_provider.dart';
import 'package:classpay/screens/admin/class_detail_screen.dart';
import 'package:classpay/screens/admin/class_form_screen.dart';
import 'package:classpay/screens/admin/class_schedule_screen.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  const classRecord = ClassRecord(
    id: 5,
    organizationId: 2,
    name: 'Year 6 Amanah',
    description: 'Morning class',
    teacherName: 'Cikgu Aina',
    startDate: null,
    endDate: null,
    status: 'inactive',
    participantCount: 20,
    hasPaymentConfiguration: false,
  );

  testWidgets('renders the class create form fields', (tester) async {
    await tester.pumpWidget(
      ProviderScope(
        child: MaterialApp(
          theme: AppTheme.light(),
          home: const ClassFormScreen(organizationId: 2),
        ),
      ),
    );

    expect(find.text('Name'), findsOneWidget);
    expect(find.text('Teacher name'), findsOneWidget);
    expect(find.text('Select start date'), findsOneWidget);
    expect(find.text('Create class'), findsOneWidget);
  });

  testWidgets('opens schedule creation controls', (tester) async {
    await tester.pumpWidget(
      ProviderScope(
        overrides: [
          classSchedulesProvider(5).overrideWith(
            (ref) async => const [
              ClassSchedule(
                id: 1,
                day: 'monday',
                startTime: '08:00',
                endTime: '10:00',
              ),
            ],
          ),
        ],
        child: MaterialApp(
          theme: AppTheme.light(),
          home: const ClassScheduleScreen(classId: 5),
        ),
      ),
    );
    await tester.pumpAndSettle();
    expect(find.text('Monday'), findsOneWidget);

    await tester.tap(find.text('Add'));
    await tester.pumpAndSettle();
    expect(find.text('Add schedule'), findsOneWidget);
    expect(find.text('Start time'), findsOneWidget);
  });

  testWidgets('explains backend schedule generation before class activation', (
    tester,
  ) async {
    await tester.pumpWidget(
      ProviderScope(
        overrides: [classProvider(5).overrideWith((ref) async => classRecord)],
        child: MaterialApp(
          theme: AppTheme.light(),
          home: const ClassDetailScreen(classId: 5),
        ),
      ),
    );
    await tester.pumpAndSettle();

    await tester.tap(find.text('Activate class'));
    await tester.pumpAndSettle();
    expect(find.text('Activate this class?'), findsOneWidget);
    expect(
      find.textContaining('Payment schedules are generated by the backend.'),
      findsOneWidget,
    );
  });
}
