import 'package:classpay/core/errors/api_error_message.dart';
import 'package:classpay/core/errors/api_exception.dart';
import 'package:classpay/core/widgets/app_card.dart';
import 'package:classpay/core/widgets/async_states.dart';
import 'package:classpay/models/class_record.dart';
import 'package:classpay/providers/class_provider.dart';
import 'package:classpay/repositories/class_repository.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

class ClassDetailScreen extends ConsumerWidget {
  const ClassDetailScreen({required this.classId, super.key});
  final int classId;
  @override
  Widget build(BuildContext context, WidgetRef ref) => ref
      .watch(classProvider(classId))
      .when(
        loading: () => const Scaffold(
          body: AppLoadingIndicator(message: 'Loading class...'),
        ),
        error: (error, stackTrace) => Scaffold(
          body: AppErrorState(
            message: apiErrorMessage(error),
            onRetry: () => ref.invalidate(classProvider(classId)),
          ),
        ),
        data: (value) => _ClassDetail(classRecord: value),
      );
}

class _ClassDetail extends ConsumerWidget {
  const _ClassDetail({required this.classRecord});
  final ClassRecord classRecord;
  @override
  Widget build(BuildContext context, WidgetRef ref) => Scaffold(
    appBar: AppBar(
      title: Text(classRecord.name),
      actions: [
        IconButton(
          tooltip: 'Edit class',
          icon: const Icon(Icons.edit_outlined),
          onPressed: () => context.push(
            '/admin/organizations/${classRecord.organizationId}/classes/${classRecord.id}/edit',
          ),
        ),
      ],
    ),
    body: ListView(
      padding: const EdgeInsets.all(16),
      children: [
        AppCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                classRecord.name,
                style: Theme.of(context).textTheme.headlineSmall,
              ),
              const SizedBox(height: 12),
              Text('Teacher: ${classRecord.teacherName}'),
              const SizedBox(height: 8),
              Text('Participants: ${classRecord.participantCount}'),
              const SizedBox(height: 8),
              Text(
                classRecord.description?.isNotEmpty == true
                    ? classRecord.description!
                    : 'No description',
              ),
              const SizedBox(height: 12),
              Chip(label: Text(classRecord.status)),
            ],
          ),
        ),
        const SizedBox(height: 16),
        AppCard(
          child: ListTile(
            leading: const Icon(Icons.schedule_outlined),
            title: const Text('Class schedules'),
            subtitle: const Text('Manage meeting days and times'),
            trailing: const Icon(Icons.chevron_right),
            onTap: () =>
                context.push('/admin/classes/${classRecord.id}/schedules'),
          ),
        ),
        const SizedBox(height: 16),
        FilledButton.icon(
          onPressed: () => _activate(context, ref),
          icon: const Icon(Icons.play_circle_outline),
          label: const Text('Activate class'),
        ),
      ],
    ),
  );
  Future<void> _activate(BuildContext context, WidgetRef ref) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Activate this class?'),
        content: const Text(
          'Activating this class generates payment schedules for active participants. Payment schedules are generated by the backend.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () => Navigator.pop(context, true),
            child: const Text('Activate'),
          ),
        ],
      ),
    );
    if (confirmed != true) return;
    try {
      final message = await ref
          .read(classRepositoryProvider)
          .activate(classRecord.id);
      if (context.mounted)
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(message.isEmpty ? 'Class activated.' : message),
          ),
        );
    } on ApiException catch (error) {
      if (context.mounted)
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text(error.message)));
    }
  }
}
